var b=Object.defineProperty;var P=Object.getOwnPropertyDescriptor;var C=Object.getOwnPropertyNames;var E=Object.prototype.hasOwnProperty;var S=(p,r)=>{for(var t in r)b(p,t,{get:r[t],enumerable:!0})},T=(p,r,t,e)=>{if(r&&typeof r=="object"||typeof r=="function")for(let a of C(r))!E.call(p,a)&&a!==t&&b(p,a,{get:()=>r[a],enumerable:!(e=P(r,a))||e.enumerable});return p};var D=p=>T(b({},"__esModule",{value:!0}),p);var L={};S(L,{default:()=>w});module.exports=D(L);var n=require("obsidian"),O={openrouterApiKey:"",inboxPath:"LaterRead/inbox.md",archivePath:"LaterRead/archive.md",digestPath:"LaterRead",autoClassify:!0},f={"aeo-geo":{emoji:"\u{1F50D}",name:"AEO/GEO"},product:{emoji:"\u{1F4E6}",name:"Product"},research:{emoji:"\u{1F4DA}",name:"Research"},market:{emoji:"\u{1F4C8}",name:"Market"},general:{emoji:"\u{1F4CC}",name:"General"}},w=class extends n.Plugin{constructor(){super(...arguments);this.items=[]}async onload(){await this.loadSettings(),await this.loadItems(),this.registerView("laterread-view",t=>new y(t,this)),this.addRibbonIcon("book-open","LaterRead",()=>{this.activateView()}),this.addCommand({id:"add-from-clipboard",name:"\u4ECE\u526A\u8D34\u677F\u6DFB\u52A0\u94FE\u63A5",callback:()=>this.addFromClipboard()}),this.addCommand({id:"add-manual",name:"\u624B\u52A8\u6DFB\u52A0\u94FE\u63A5",callback:()=>new x(this.app,this).open()}),this.addCommand({id:"generate-digest",name:"\u751F\u6210\u5468\u672B\u9605\u8BFB\u6E05\u5355",callback:()=>this.generateDigest()}),this.addCommand({id:"open-laterread",name:"\u6253\u5F00 LaterRead \u9762\u677F",callback:()=>this.activateView()}),this.addCommand({id:"archive-all-read",name:"\u5F52\u6863\u6240\u6709\u5DF2\u8BFB",callback:()=>this.archiveAllRead()}),this.addSettingTab(new I(this.app,this)),this.registerEvent(this.app.vault.on("modify",t=>{t.path===this.settings.inboxPath&&this.loadItems()}))}async activateView(){let{workspace:t}=this.app,e=t.getLeavesOfType("laterread-view")[0];e||(e=t.getRightLeaf(!1),await e.setViewState({type:"laterread-view",active:!0})),t.revealLeaf(e)}async loadSettings(){this.settings=Object.assign({},O,await this.loadData())}async saveSettings(){await this.saveData(this.settings)}async loadItems(){let t=this.app.vault.getAbstractFileByPath(this.settings.inboxPath);if(!t||!(t instanceof n.TFile)){this.items=[];return}let e=await this.app.vault.read(t);this.items=this.parseMarkdown(e),this.app.workspace.getLeavesOfType("laterread-view").forEach(a=>{a.view instanceof y&&a.view.refresh()})}parseMarkdown(t){let e=[],a=t.split(`
`),s=null;for(let i of a){let o=i.match(/^- \[([ x])\] ([🔍📦📚📈📌]) \[(.+?)\]\((.+?)\) \| (.+?) \| (.+?)$/);if(o){let[,d,h,c,l,g,u]=o,m=Object.entries(f).find(([,R])=>R.emoji===h)?.[0]||"general";e.push({id:this.generateId(),url:l,title:c,domain:g,summary:"",category:m,note:"",createdAt:u,isRead:d==="x"})}i.startsWith(">  ")&&e.length>0&&(e[e.length-1].summary=i.substring(3)),i.startsWith("> \u{1F4DD} ")&&e.length>0&&(e[e.length-1].note=i.substring(5))}return e}async saveItems(){let t=this.generateMarkdown(),e=this.app.vault.getAbstractFileByPath(this.settings.inboxPath);if(e&&e instanceof n.TFile)await this.app.vault.modify(e,t);else{let a=this.settings.inboxPath.substring(0,this.settings.inboxPath.lastIndexOf("/"));a&&!this.app.vault.getAbstractFileByPath(a)&&await this.app.vault.createFolder(a),await this.app.vault.create(this.settings.inboxPath,t)}}generateMarkdown(){let t=`# \u{1F4D6} LaterRead Inbox

`,e={};for(let s of this.items)e[s.category]||(e[s.category]=[]),e[s.category].push(s);let a=["aeo-geo","product","research","market","general"];for(let s of a){let i=e[s];if(!i||i.length===0)continue;let o=f[s];t+=`## ${o.emoji} ${o.name}

`;for(let d of i){let h=d.isRead?"x":" ",c=f[d.category]?.emoji||"\u{1F4CC}";t+=`- [${h}] ${c} [${d.title}](${d.url}) | ${d.domain} | ${d.createdAt}
`,d.summary&&(t+=`>  ${d.summary}
`),d.note&&(t+=`> \u{1F4DD} ${d.note}
`),t+=`
`}}return t}async addFromClipboard(){let e=(await navigator.clipboard.readText()).match(/https?:\/\/[^\s]+/);if(!e){new n.Notice("\u526A\u8D34\u677F\u4E2D\u6CA1\u6709\u627E\u5230\u6709\u6548\u94FE\u63A5");return}let a=e[0];await this.addItem(a)}async addItem(t,e=""){let a=t,s="unknown";try{s=new URL(t).hostname.replace("www.","");let c=(await(await fetch(t)).text()).match(/<title>([^<]+)<\/title>/i);c&&(a=c[1].trim())}catch(o){console.log("Failed to fetch page info:",o)}let i={id:this.generateId(),url:t,title:a,domain:s,summary:"",category:"general",note:e,createdAt:new Date().toISOString().split("T")[0],isRead:!1};if(this.settings.autoClassify&&this.settings.openrouterApiKey)try{let o=await this.classifyWithAI(i);i.summary=o.summary,i.category=o.category}catch(o){console.log("AI classification failed:",o)}this.items.unshift(i),await this.saveItems(),new n.Notice(`\u2713 \u5DF2\u4FDD\u5B58: ${i.title}`),this.app.workspace.getLeavesOfType("laterread-view").forEach(o=>{o.view instanceof y&&o.view.refresh()})}async classifyWithAI(t){let s=(await(await fetch("https://openrouter.ai/api/v1/chat/completions",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${this.settings.openrouterApiKey}`},body:JSON.stringify({model:"google/gemini-3-pro-preview",max_tokens:200,messages:[{role:"user",content:`Analyze this article and provide:
1. A brief summary (1-2 sentences, max 80 characters)
2. Category classification

Title: ${t.title}
URL: ${t.url}
Domain: ${t.domain}

Categories:
- aeo-geo: AI search optimization, SEO, GEO, AEO
- product: Products, tools, apps, startups
- research: Academic papers, methodologies
- market: Finance, investing, markets
- general: Everything else

Respond in JSON only: {"summary": "...", "category": "..."}`}]})})).json()).choices?.[0]?.message?.content||"{}";try{let i=s.match(/\{[\s\S]*\}/);if(i)return JSON.parse(i[0])}catch(i){console.log("Failed to parse AI response:",i)}return{summary:"",category:"general"}}async markAsRead(t,e=!0){t.isRead=!0,e&&(await this.archiveItem(t),this.items=this.items.filter(a=>a.id!==t.id)),await this.saveItems()}async deleteItem(t){this.items=this.items.filter(e=>e.id!==t.id),await this.saveItems()}async archiveItem(t){let e=this.settings.archivePath,a=e.substring(0,e.lastIndexOf("/"));a&&!this.app.vault.getAbstractFileByPath(a)&&await this.app.vault.createFolder(a);let s="",i=this.app.vault.getAbstractFileByPath(e);i&&i instanceof n.TFile?s=await this.app.vault.read(i):s=`# \u{1F4DA} LaterRead Archive

`;let o=new Date,h=`## \u{1F4C5} ${`${o.getFullYear()}-${(o.getMonth()+1).toString().padStart(2,"0")}`}`,l=`- [x] ${(f[t.category]||f.general).emoji} [${t.title}](${t.url}) | ${t.domain} | ${t.createdAt}
`;if(t.summary&&(l+=`>  ${t.summary}
`),t.note&&(l+=`> \u{1F4DD} ${t.note}
`),l+=`
`,s.includes(h)){let u=s.indexOf(h)+h.length+2;s=s.slice(0,u)+l+s.slice(u)}else{let g=s.indexOf(`

`)+2,u=`${h}

${l}`;s=s.slice(0,g)+u+s.slice(g)}i&&i instanceof n.TFile?await this.app.vault.modify(i,s):await this.app.vault.create(e,s),new n.Notice(`\u{1F4DA} \u5DF2\u5F52\u6863: ${t.title}`)}async archiveAllRead(){let t=this.items.filter(e=>e.isRead);if(t.length===0){new n.Notice("\u6CA1\u6709\u5DF2\u8BFB\u6761\u76EE\u9700\u8981\u5F52\u6863");return}for(let e of t)await this.archiveItem(e);this.items=this.items.filter(e=>!e.isRead),await this.saveItems(),new n.Notice(`\u2713 \u5DF2\u5F52\u6863 ${t.length} \u7BC7\u6587\u7AE0`)}async generateDigest(){let t=this.items.filter(l=>!l.isRead);if(t.length===0){new n.Notice("\u6CA1\u6709\u5F85\u8BFB\u5185\u5BB9");return}let e=new Date,a=this.getWeekNumber(e),s=`${this.settings.digestPath}/${e.getFullYear()}-W${a.toString().padStart(2,"0")}.md`,i=`# \u{1F4DA} \u5468\u672B\u9605\u8BFB\u6E05\u5355 ${e.getFullYear()}-W${a}

`;i+=`> \u751F\u6210\u4E8E ${e.toLocaleDateString("zh-CN")} \xB7 \u5171 ${t.length} \u7BC7\u5F85\u8BFB

---

`;let o={};for(let l of t)o[l.category]||(o[l.category]=[]),o[l.category].push(l);let d=["aeo-geo","product","research","market","general"];for(let l of d){let g=o[l];if(!g||g.length===0)continue;let u=f[l];i+=`## ${u.emoji} ${u.name}

`;for(let m of g)i+=`### [${m.title}](${m.url})

`,i+=`- **\u6765\u6E90**: ${m.domain}
`,i+=`- **\u6DFB\u52A0**: ${m.createdAt}
`,m.summary&&(i+=`- **\u6458\u8981**: ${m.summary}
`),m.note&&(i+=`
> \u{1F4DD} ${m.note}
`),i+=`
`}i+=`---

*\u7531 LaterRead \u81EA\u52A8\u751F\u6210*`;let h=this.app.vault.getAbstractFileByPath(s);h&&h instanceof n.TFile?await this.app.vault.modify(h,i):await this.app.vault.create(s,i),new n.Notice(`\u2713 \u5DF2\u751F\u6210: ${s}`);let c=this.app.vault.getAbstractFileByPath(s);c&&c instanceof n.TFile&&this.app.workspace.getLeaf().openFile(c)}getWeekNumber(t){let e=new Date(t.getFullYear(),0,1),a=(t.getTime()-e.getTime())/864e5;return Math.ceil((a+e.getDay()+1)/7)}generateId(){return Math.random().toString(36).substring(2,9)}},y=class extends n.ItemView{constructor(r,t){super(r),this.plugin=t}getViewType(){return"laterread-view"}getDisplayText(){return"LaterRead"}getIcon(){return"book-open"}async onOpen(){this.refresh()}refresh(){let r=this.containerEl.children[1];r.empty();let t=r.createDiv({cls:"laterread-header"});t.createEl("h4",{text:"\u{1F4D6} LaterRead"});let e=t.createDiv({cls:"laterread-stats"}),a=this.plugin.items.filter(c=>!c.isRead).length;e.setText(`${a} \u7BC7\u5F85\u8BFB`);let s=r.createDiv({cls:"laterread-toolbar"}),i=s.createEl("button",{text:"+ \u6DFB\u52A0"});i.onclick=()=>new x(this.app,this.plugin).open();let o=s.createEl("button",{text:"\u{1F4CB} Digest"});o.onclick=()=>this.plugin.generateDigest();let d=s.createEl("button",{text:"\u{1F4DA} \u5F52\u6863\u5DF2\u8BFB"});d.onclick=()=>this.plugin.archiveAllRead().then(()=>this.refresh());let h=r.createDiv({cls:"laterread-list"});if(this.plugin.items.length===0){h.createDiv({cls:"laterread-empty",text:`\u6682\u65E0\u5F85\u8BFB\u5185\u5BB9
\u6309 Ctrl/Cmd+P \u641C\u7D22 "LaterRead" \u6DFB\u52A0`});return}for(let c of this.plugin.items.filter(l=>!l.isRead)){let l=h.createDiv({cls:"laterread-item"}),g=l.createDiv({cls:"laterread-item-title"}),u=f[c.category]||f.general;g.createSpan({text:u.emoji+" "});let m=g.createEl("a",{text:c.title,href:c.url});m.onclick=v=>{v.preventDefault(),window.open(c.url,"_blank")},l.createDiv({cls:"laterread-item-meta"}).setText(`${c.domain} \xB7 ${c.createdAt}`),c.summary&&l.createDiv({cls:"laterread-item-summary"}).setText(c.summary),c.note&&l.createDiv({cls:"laterread-item-note"}).setText("\u{1F4DD} "+c.note);let k=l.createDiv({cls:"laterread-item-actions"}),$=k.createEl("button",{text:"\u2713 \u5DF2\u8BFB"});$.onclick=async()=>{await this.plugin.markAsRead(c),this.refresh()};let A=k.createEl("button",{text:"\u2715"});A.onclick=async()=>{await this.plugin.deleteItem(c),this.refresh()}}this.addStyles()}addStyles(){let r=document.getElementById("laterread-styles")||document.createElement("style");r.id="laterread-styles",r.textContent=`
      .laterread-header { display: flex; justify-content: space-between; align-items: center; padding: 10px; border-bottom: 1px solid var(--background-modifier-border); }
      .laterread-header h4 { margin: 0; }
      .laterread-stats { font-size: 12px; color: var(--text-muted); }
      .laterread-toolbar { display: flex; gap: 8px; padding: 10px; border-bottom: 1px solid var(--background-modifier-border); }
      .laterread-toolbar button { font-size: 12px; padding: 4px 8px; }
      .laterread-list { padding: 10px; }
      .laterread-empty { text-align: center; color: var(--text-muted); padding: 20px; white-space: pre-line; }
      .laterread-item { padding: 10px; margin-bottom: 8px; background: var(--background-secondary); border-radius: 6px; }
      .laterread-item-title { font-weight: 500; margin-bottom: 4px; }
      .laterread-item-title a { color: var(--text-normal); text-decoration: none; }
      .laterread-item-title a:hover { color: var(--text-accent); }
      .laterread-item-meta { font-size: 11px; color: var(--text-muted); margin-bottom: 4px; }
      .laterread-item-summary { font-size: 12px; color: var(--text-muted); margin-bottom: 4px; }
      .laterread-item-note { font-size: 12px; color: var(--text-accent); }
      .laterread-item-actions { display: flex; gap: 8px; margin-top: 8px; }
      .laterread-item-actions button { font-size: 11px; padding: 2px 6px; }
    `,document.head.appendChild(r)}},x=class extends n.Modal{constructor(t,e){super(t);this.url="";this.note="";this.plugin=e}onOpen(){let{contentEl:t}=this;t.createEl("h3",{text:"\u6DFB\u52A0\u5230 LaterRead"}),new n.Setting(t).setName("URL").addText(e=>{e.setPlaceholder("https://..."),e.onChange(a=>this.url=a),navigator.clipboard.readText().then(a=>{a.match(/^https?:\/\//)&&(e.setValue(a),this.url=a)})}),new n.Setting(t).setName("\u5907\u6CE8").addText(e=>{e.setPlaceholder("\u53EF\u9009\u5907\u6CE8..."),e.onChange(a=>this.note=a)}),new n.Setting(t).addButton(e=>{e.setButtonText("\u4FDD\u5B58"),e.setCta(),e.onClick(async()=>{if(!this.url){new n.Notice("\u8BF7\u8F93\u5165 URL");return}await this.plugin.addItem(this.url,this.note),this.close()})}).addButton(e=>{e.setButtonText("\u53D6\u6D88"),e.onClick(()=>this.close())})}onClose(){this.contentEl.empty()}},I=class extends n.PluginSettingTab{constructor(r,t){super(r,t),this.plugin=t}display(){let{containerEl:r}=this;r.empty(),r.createEl("h2",{text:"LaterRead \u8BBE\u7F6E"}),new n.Setting(r).setName("OpenRouter API Key").setDesc("\u7528\u4E8E\u81EA\u52A8\u5206\u7C7B\u548C\u751F\u6210\u6458\u8981 (\u4F7F\u7528 Gemini 3 Pro)").addText(t=>t.setPlaceholder("sk-or-...").setValue(this.plugin.settings.openrouterApiKey).onChange(async e=>{this.plugin.settings.openrouterApiKey=e,await this.plugin.saveSettings()})),new n.Setting(r).setName("\u81EA\u52A8\u5206\u7C7B").setDesc("\u6DFB\u52A0\u65F6\u81EA\u52A8\u8C03\u7528 AI \u5206\u7C7B").addToggle(t=>t.setValue(this.plugin.settings.autoClassify).onChange(async e=>{this.plugin.settings.autoClassify=e,await this.plugin.saveSettings()})),new n.Setting(r).setName("Inbox \u6587\u4EF6\u8DEF\u5F84").addText(t=>t.setValue(this.plugin.settings.inboxPath).onChange(async e=>{this.plugin.settings.inboxPath=e,await this.plugin.saveSettings()})),new n.Setting(r).setName("Digest \u76EE\u5F55").addText(t=>t.setValue(this.plugin.settings.digestPath).onChange(async e=>{this.plugin.settings.digestPath=e,await this.plugin.saveSettings()}))}};
